changelog = true
[[classOrder]]
section = "Core API"
classes = ["ChatConfig","ChatStyling","Command","RealmCommand","ChatCommands","ChatCore"]
[[classOrder]]
section = "Server API"
classes = ["ChatMonitor","ChatChannel","ChatboxExtended"]
[[classOrder]]
section = "Client API"
classes = ["ChatUI","ChatChannelC","ChatboxExtendedC"]